### ISSUE TITLE
add an option to post-process minimal nemo variables for ECMean

### ISSUE THREAD

**Issue by etiennesky** [plesager/ece3-postproc#14]
current hiresclim2 post-nemo.sh does many time-consuming calculations which are not use by ECMean , even with nemo_extra=0, such as calls to cdfheatc cdfmoc and cdficediags

It would be nice to identify which variables are needed and to only calculate them if a flag is set (tentatively called nemo_basic, maybe  could be nemo_ecmean).

Any thoughts?

**Comment by plesager** [comment]
Why not? I noticed that the NEMO part was slower, but not much of an issue for me. Do you have timings?

**Comment by etiennesky** [comment]
Hi I did in the past but lost them. I would say about 2 minutes vs 5 minutes for 1 year lowres, so not insignificant if doing long runs, especially at HR.

I have a simple change which works, moving the nino34 and heatc computations into the nemo_extra part.

This will have to be revised when the timeseries works.

**Comment by etiennesky** [comment]
In fact, my solution does not involve having a new config variable, simply computes these variables if nemo_extra=1

**Comment by oloapinivad** [comment]
I agree on this: second order NEMO results are provided by barakuda directly from the output, so we probably don't need them for hiresclim. I guess the main choiche will depend mainly if we want to maintain or not the oceanic timeseries

**Comment by etiennesky** [comment]
closing this issue as my changes have been merged by Philippe
