### ISSUE TITLE
fix timeseries plots

### ISSUE THREAD

**Issue by etiennesky** [plesager/ece3-postproc#15]
currently timeseries plots are unusable: for the atmosphere, years overlap instead of being sequential, and nemo plots are just unreadable.

**Comment by plesager** [comment]
I have not tried to run the timeseries in a very long time. If I remember, the nemo part is very much a subset of barakuda. I suspect nobody is using it? Initially t does look like a good idea to quickly get some usual timeseries plot, but (I guess) people have their own plot routine that are more flexible (e.g. comparing several experiments in one plot, ....)

**Comment by etiennesky** [comment]
I agree that the nemo part might not be so important (since barakuda does it better), bu the atmosphere plots are interesting and is quick.

**Comment by oloapinivad** [comment]
I agree that the Nemo part is deprecated now since barakuda is a comprehensive extension of it. 

However as long as I remember at ISAC we have a working version, at least for the atmospheric part. If you let me a few days I will talk with @abalanzino that has run it for a while, we can try to pull our local version (not in GitHub yet).

**Comment by etiennesky** [comment]
Attaching here plots of atmosphere (msl) and ocean (sst) to illustrate the problem.

![msl_a0wy](https://user-images.githubusercontent.com/1018556/36842037-a9c965e4-1d4a-11e8-8632-5576053911a8.png)

![sosstsst_a0wy](https://user-images.githubusercontent.com/1018556/36842036-a9aad354-1d4a-11e8-855e-a119d975579c.png)

**Comment by etiennesky** [comment]
Although nemo is deprecated, Barakuda is not so easy to setup so if we could have some key variables plotted it would be helpful.

**Comment by abalanzino** [comment]
Paolo, I confirm we have a working version of timeseries!

**Comment by oloapinivad** [comment]
@abalanzino worked on this last week, we are almost ready to pull our updated version. We added a -u USERexp flag also for this. 

Some examples:

<img width="1230" alt="schermata 2018-03-08 alle 14 02 36" src="https://user-images.githubusercontent.com/28352235/37152357-65d5e134-22d9-11e8-83fa-40fe6f04135d.png">
<img width="1247" alt="schermata 2018-03-08 alle 14 02 25" src="https://user-images.githubusercontent.com/28352235/37152365-6911ddbc-22d9-11e8-9a38-8d81c1d360b6.png">

**Comment by etiennesky** [comment]
brillant! nice work!

**Comment by etiennesky** [comment]
brilliant! with your changes I can get the atmospheric and ocean timeseries.

The only problem is the AMOC value which are 0, but this is because somehow cdfmoc sets depthw to 0 on all levels... any idea? I am using cdftools-3.1

**Comment by etiennesky** [comment]
I am still having problems with the maxmoc, cdfmoc sets depthw to 0 .

I tried both cdftools 3.0.1 and 3.0.2. What version are you using @abalanzino @oloapinivad ? Thanks!

**Comment by abalanzino** [comment]
We are using cdftools_3.0.

**Comment by plesager** [comment]
Since nothing is documented, and I'm not in the mood to read more code today, let me ask:
1) do we expect plots or just netcdf files? I only have the later and no hint in the log about the former.
2) I have a lot of `problem` warnings:

2a) The program seems confused by the year range. I keep reading while processing 1950-1969:

> PROBLEM: we cannot find /nfs/home/users/sager/EC-Earth/diag//timeseries/n_05/ocean/n_05_1951_1969_time-series_ocean.nc !!!

2b) and is clueless about amoc:

> Doing AMOC
>  *** File /lustre3/projects/CMIP6/sager/rundirs/n_05/post/mon/Post_????/n_05_1969_moc.nc not here! Skipping variable zomsfatl !

**Comment by etiennesky** [comment]
Hi @plesager 

1. there is a small netcdf file, some svg plots and a index.html
2a). no clue...
2b) hiresclim2 has to create the *moc.nc file which is currently in the extras section

I have some fixes coming I will let you know.

**Comment by etiennesky** [comment]
If you merge my latest MR moc is computed in nemo_post.sh even without nemo_extra=1 .

Somehow cdftools does not  read properly the depthw variable in mesh_zgr.nc supplied with this tool , resulting in a 0 MOC. With cdftools-3.0.1 I had to do the following command in the DATADIR:

ncrename -v gdepw_0,gdepw_0_bak mesh_zgr.nc

@plesager I suggest you delete you post and diags and re-run hiresclim2 and then timeseries.

timeseries, like barakuda, requires you to delete the timeseries files it creates if something goes wrong.

In any case I think the log you mention in 2a) is not really a bug, it just means it didn't find the timeseries file so it starts from 0.

With this latest MR I am able to plot atmosphere and ocean timeseries.

**Comment by abalanzino** [comment]
We had no problem with AMOC values (we are using cdftools release 3.0).
I'm sorry, but we didn't write the timeseries code. It results from an original code of Laurent Brodeaux (a code which had to be adjusted).

**Comment by plesager** [comment]
Got it to work on Rhino (see dcca94e, which also removes a lot of white space in the code and the log). The bug: it assumed there was no underscore in the EXPID. Which I had in my experiments. On the other hand, no problem with cdftools-4 to get the AMOC.
Still need to test on cca.

**Comment by plesager** [comment]
It is working on cca. Bug fix (unbound BASE_YEAR_INI), and easy check for success at the CLI have been committed (be6694b) along the cca config.
