### ISSUE TITLE
barakuda as submodule?

### ISSUE THREAD

**Issue by oloapinivad** [plesager/ece3-postproc#27]
Hi all,

since this is becoming the official tool for ecearth3, I was wondering if it makes sense to include barakuda as a submodule of ece3-postproc repository. 
I know that barakuda uses its own configuration files and structures, but we can think about introducing a wrapper that call it in the script folder. 
What do you think?
Ciao
Paolo

**Comment by plesager** [comment]
I can understand the will to get all postprocessing tools under the same umbrella, but barakuda is used outside EC-Earth and it is then easier to maintain if we do not include it here. I guess it is possible, but I am not fluent enough in git and have too little time to invest to go down this road. Anyway, Thomas Arsouze from BSC will be maintaining and developing barakuda for EC-Earth: to make it work with cmorized output, remove the dependency on tailored cdftools, and more.
