### ISSUE TITLE
Hiresclim not working for historical run output

### ISSUE THREAD

**Issue by jmrgonza** [plesager/ece3-postproc#45]
Hi,

I am getting some errors using the hc.sh script with my historical run output. The job output indicates a problem with the dimension of some array.
```
file for Q => /scratch/ms/es/spk/ECEARTH-RUNS/HIST/post/mon/Post_1850/HIST_1850_q.nc
file for T => /scratch/ms/es/spk/ECEARTH-RUNS/HIST/post/mon/Post_1850/HIST_1850_t.nc
File for RH to create: /scratch/ms/es/spk/ECEARTH-RUNS/HIST/post/mon/Post_1850/HIST_
1850_r.nc


 Opening file /scratch/ms/es/spk/ECEARTH-RUNS/HIST/post/mon/Post_1850/HIST_1850_q.nc

43 pressure levels:
[ 100000.   97500.   95000.   92500.   90000.   87500.   85000.   82500.
   80000.   77500.   75000.   70000.   65000.   60000.   55000.   50000.
   45000.   40000.   35000.   30000.   25000.   22500.   20000.   17500.
   17000.   15000.   13000.   12500.   11500.   10000.    9000.    8000.
    7000.    5000.    3000.    2000.    1500.    1000.     700.     500.
     300.     200.     100.] 

LONGITUDE:  degrees_east
LATGITUDE:  degrees_north
TIME:  hours since 1850-01-01 00:00:00 


 Opening file /scratch/ms/es/spk/ECEARTH-RUNS/HIST/post/mon/Post_1850/HIST_1850_t.nc

Units for T is K
Shape problem!!!
(12, 43, 256, 512) (12, 11, 256, 512)
 Shape of fields is  512 256 43 12 

 Time =  1
Traceback (most recent call last):
  File "../rhbuild/build_RH_new.py", line 141, in <module>
    xE_sat[:,:] = mifse.e_sat(xT[jt,jk,:,:])
IndexError: index 11 is out of bounds for axis 1 with size 11

```
In the /scratch/ms/es/spk/ECEARTH-RUNS/HIST/post/mon/Post_1850/HIST_1850_t.nc file, I can see that the number of levels does not correspond to the above one for HIST_1850_q.nc, because the levels from 100000 to 75000 Pa are missing.
Greetings,
Chema

**Comment by plesager** [comment]
Indeed the relative humidity cannot be calculated. I haven't try to fix it. But you can switch that computation off in `conf/cca/conf_hiresclim_cca.sh` with `rh_build=0`.

**Comment by jmrgonza** [comment]
It works for me with rh_build=0, but is it on purpose that the output in HIST_<yyyy>_t.nc does not include pressure levels bellow 700 hPa?

**Comment by jmrgonza** [comment]
It looks like a cdo issue. I reverted the change in cdo version that you made related to #36 and the script completed with rh_build=1. I used cdo/1.8.2.

**Comment by plesager** [comment]
Ok, but `cdo/1.8.2` has its own issue #36. Maybe it is worth trying `cdo/1.9.x`.

**Comment by oloapinivad** [comment]
On cca, for me it works fine with `cdo/1.9.6`

**Comment by plesager** [comment]
Hardcoded `cdo` version in 6699891
