### ISSUE TITLE
Timeseries MOC with no value

### ISSUE THREAD

**Issue by oloapinivad** [plesager/ece3-postproc#46]
Since barakuda is no longer maintained, I am back on the timeseries.sh for monitoring the CMIP6 runs. They works fine on cca. 

However, I noticed that MOC plots are empty. At first sight, it seems that the horizontal grid become "generic" for the *_moc.nc file so when NCO tries to extract the maximum at a fixed latitude it produce a zero-value. Did anybody see the same?

**Comment by oloapinivad** [comment]
I found out that this is actually #2 . I solved this compiling cdftools4 on cca.

**Comment by plesager** [comment]
OK, good to know, thanks.
