### ISSUE TITLE
NEMO monitoring crash

### ISSUE THREAD

**Issue by plesager** [plesager/ece3-postproc#47]
Got this error message from `monitor_ocean.sh` of `hiresclim2`:

> #[17:23:33] monitor_ocean.sh[476]> ncks -3 -h -A -v tot_area_ice_north tmp_north.nc -o atun_1870_time-series_ocean.tmp
> nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco_put_vara()
> nco_err_exit(): ERROR Error code is -57. Translation into English with nc_strerror(-57) is "NetCDF: Start+count exceeds dimension bound"
> ERROR: nco_put_vara() failed to nc_put_vara() variable "nav_lat"
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)

Not sure with which version of EC-Earth output this started, and if this is specific to ECMWF/cca platform. But I have the error with both CMIP6 and vanilla control output files of EC-Earth (essentially a version that will be 3.3.1.1).

**Comment by oloapinivad** [comment]
Which version of NCO are you using? 
I am currently using the following modules `nco/4.6.7 netcdf python/2.7.12-01 cdo/1.9.6`. I am monitoring a historical simulation with r6903 which is basically the same as 3.3.1.1. and the timeseries subpackage works smooth.

**Comment by plesager** [comment]
I tried both older `nco/4.3.7` and newest  `nco/4.7.8`. Maybe I should try `4.6.7`....
I have `cdo/1.9.6` but that does not matter here I think.

**Comment by plesager** [comment]
Ok, I figured it out. `nco/4.7.8` became the default on ECMWF/cca in June 2019 and that was creating the problem.  Switching back to 4.6.7 fixes it. Thanks @oloapinivad

**Comment by plesager** [comment]
Committed fix 6699891
