### ISSUE TITLE
cdftools version

### ISSUE THREAD

**Issue by plesager** [plesager/ece3-postproc#6]
there are issues with different versions of CDFtools. Etienne only managed to get cdftools 3.0.1 to work for example. At ECMWF (cca) we have 3.0 (minor revision unknown). On the Bull at KNMI, I have 4.0.

The current README https://github.com/meom-group/CDFTOOLS:
"The last version 3's release has been tagged as v3.0.2. Use this tag if you want to stay at version 3."

Could we stick to one version which we know works for everything?

**Comment by oloapinivad** [comment]
On Marconi we have CDFTOOLS 3.0, but again we do not know minor revision. It is working fine.

**Comment by plesager** [comment]
Good to know. I am afraid we have to leave with the assumption of various versions around. Hopefully there are not too many cases around. Looks like we have already three cases for four machines though!

**Comment by etiennesky** [comment]
Hi @plesager can we try and stick to one version e.g. 3.0.2 ? 

It is pretty easy to compile & install it ourselves.  

I can upgrade to 3.0.2 instead of 3.0.1

**Comment by plesager** [comment]
We have a code working with 3.0, 3.01, and 4.0.
I would prefer not to force a version. Not every user is willing to install a library however easy it is, and repeat the process at every system update if needed. Moreover the change of syntax we are concerned with should not change all the time with every release of CDFTOOLS.
So I am closing the issue. We can start a new one, or reopen this one, if another version of cdftools is being tested and causes problem.
