### ISSUE TITLE
update to newer version of CDO

### ISSUE THREAD

**Issue by oloapinivad** [plesager/ece3-postproc#7]
On Marconi we have CDO 1.8.2. I have seen that there is the "lev" - "plev" inconsistency in build_RH_new.py, resulting in a crash of the script. 
Wouldn't be better to use "plev" and move to newer CDO versions? 
It is not urgent but perhaps it is worth the shot. 
Cheers,
Paolo

**Comment by plesager** [comment]
I put a fix in 07ef3c7862ab11808027afe091aa67a5b7dfde4b commit, which should work with old and new cdo. I think this is the way to go, since we cannot expect users to install a newer cdo if needed, particularly on HPC.

**Comment by oloapinivad** [comment]
I have seen it now, thanks a lot. Definitely the best solution, thanks.
